# Generated by Django 2.1.7 on 2019-04-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrders', '0002_auto_20190410_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='workOrders.User'),
            preserve_default=False,
        ),
    ]
