# Generated by Django 2.1.7 on 2019-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrders', '0003_job_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='job_types',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
