# Generated by Django 2.1.7 on 2019-04-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrders', '0006_job_request_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='PO_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='workOrders.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker', to='workOrders.Worker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
