# Generated by Django 2.1.7 on 2019-04-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrders', '0007_auto_20190410_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
